### ISSUE TITLE
Limited to 9 receivers

### ISSUE THREAD

**Issue by CedricAlb** [maciejzgadzaj/commerce_marketplace_paypal#1]
I just created my first repository on Github to share a very small module to limit the checkout when using a PayPal Chained payment as it is limited by PayPal to 9 secondary receivers.
https://github.com/CedricAlb/commerce_marketplace_paypal_chained
You could maybe adapt it to complete Commerce Marketplace PayPal...

**Comment by maciejzgadzaj** [comment]
Thanks for this Cedric! Yes, adding some kind of verification for this is on my 'dev release blockers' list (probably I should create issues here for each item on my generic 'to do' list).

Just one question - where did you take that 9 from? I haven't actually tested it yet, but Adaptive Payments documentation talks about 6 receivers max, both for parallel and chained payments - see https://developer.paypal.com/docs/classic/api/adaptive-payments/Pay_API_Operation/ - in `receiverList.receiver(n).email` description.

**Comment by CedricAlb** [comment]
I found the 9 here : https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/

> You can have at most one primary receiver and 1-9 secondary receivers.

But I think you're right for 6, the API docs are more accurate. I need to do some testing tomorrow...

**Comment by CedricAlb** [comment]
I just tested a transaction with 1 primary and 10 secondary receivers via your module (marketplace_fees branch) and the error message from the sandbox is confirming the limit of 9 secondary receivers, see : 

```
Adaptive Payments: failed to retrieve the pay key for order 20, 11, 12, 13, 14, 15, 16, 17, 18, 19. PayPal response:
stdClass Object
(
    [responseEnvelope] => stdClass Object
        (
            [timestamp] => 2015-04-27T02:26:20.901-07:00
            [ack] => Failure
            [correlationId] => f151a9e37ce26
            [build] => 15743565
        )
    [error] => Array
        (
            [0] => stdClass Object
                (
                    [errorId] => 579007
                    [domain] => PLATFORM
                    [subdomain] => Application
                    [severity] => Error
                    [category] => Application
                    [message] => The maximum number of receivers is 10
                    [parameter] => Array
                        (
                            [0] => 10
                        )
                )
        )
)
```

**Comment by maciejzgadzaj** [comment]
Limit added in https://github.com/maciejzgadzaj/commerce_marketplace_paypal/commit/9a38d8fd3585e10bf023f41bd8f17c9ef83d45a8
